# Role
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: gzr-namespace
  name: example-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: gzr-namespace
  name: example-sa
---
# RoleBinding
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-rolebinding
  namespace: gzr-namespace
subjects:
  - kind: ServiceAccount
    name: example-sa
    namespace: gzr-namespace
roleRef:
  kind: Role
  name: example-role
  apiGroup: rbac.authorization.k8s.io