apiVersion: v1
kind: Pod
metadata:
  name: host-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:1.8
  hostAliases:
  - ip: "10.0.0.0"
    hostnames:
    - "foo.remote"
    - "bar.remote"

