apiVersion: v1
kind: Pod
metadata:
  name: nginx-volume-nfs
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-storage-nfs
  volumes:
    - name: nginx-storage-nfs
      nfs:
        path: /home/data
        server: 192.168.50.234