apiVersion: v1
kind: Pod
metadata:
  name: nginx-volume
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-storage1
  volumes:
    - name: nginx-storage1
      hostPath:
        path: /home/html