apiVersion: v1
kind: Pod
metadata:
  name: pv-nfs-web
  labels:
    name: web-frontend
spec:
  containers:
  - name: web
    image: nginx
    ports:
      - containerPort: 80
        name: web
    resources:
      limits:
        cpu: 500m
        memory: 1000Mi
      requests:
        cpu: 200m
        memory: 500Mi
    volumeMounts:
      - name: nfs
        mountPath: "/usr/share/nginx/html"
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: nfs
