kind: Secret
apiVersion: v1
metadata:
  name: db-secret
data:
  # admin
  username: YWRtaW4=
  # 123456
  password: MTIzNDU2
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod-secret1
spec:
  containers:
  - name: mypod
    image: nginx
    volumeMounts:
    - name: test-db
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: test-db
    secret:
      secretName: db-secret